title: Learn to Live
author: nik
email: nik@domain.com
description: > # this means to ignore newlines until "baseurl:"
  'We live to learn, however each new day, we Learn to Live'
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
