title: Awesome day
author: nik
email: nwaborkingsley@gmail.com
description: Every day we Live to Learn however most importantly is that each moment we Learn to Live.

twitter_username: yongdocofficial
github_username:  Ifeanyi-Kingsley-Nwabor
show_excerpts: false 
